FROM nvcr.io/nvidia/deepstream:7.0-triton-multiarch

RUN apt-get update && apt-get install

ENV NVIDIA_DRIVER_CAPABILITIES=$NVIDIA_DRIVER_CAPABILITIES,video

RUN apt-get -y install python3-pip bash wget cmake g++ build-essential libtool m4 \
    autoconf automake libgirepository1.0-dev libcairo2-dev python3-gi python3-dev python3-gst-1.0

# pyds 1.2.2 for deepstream 8.0
RUN wget https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/releases/download/v1.1.11/pyds-1.1.11-py3-none-linux_x86_64.whl && \
    pip3 install ./pyds-1.1.11-py3-none-linux_x86_64.whl;

RUN pip3 install opencv-python cupy-cuda12x
